### ISSUE TITLE
How to use with highlight.js?

### ISSUE THREAD

**Issue by ajbraus** [btford/angular-markdown-directive#47]
I was deciding between angular markdown directives and being able to use highlight.js was the deciding factor. Is there a way it works with this directive?

**Comment by albalitz** [comment]
I also just tried using angular-markdown-directive with highlight.js and wasn't able to get this to work.

However, I just discovered [angular-marked](https://github.com/Hypercubed/angular-marked), which is based on this project and uses highlight.js. It's really easy to set up and it works perfectly. ;)

So, if you (or anyone else with the same goal) are still looking for this function, I highly recommend checking out angular-marked.
