### ISSUE TITLE
Attribute Support

### ISSUE THREAD

**Issue by neilkyoung** [btford/angular-markdown-directive#51]
Does this directive support assigning attributes in Markdown? Specifically adding classes and ids.

**Comment by JLRishe** [comment]
I don't believe markdown has conventions for adding attributes, but you can always mix raw HTML in with your markdown and yes, this directive allows you to do that.

**Comment by neilkyoung** [comment]
I ended up writing a couple of extensions to handle this after seeing you can supply these to showdown.js via a config provider:

`
//extensions to configure different classes for images
    var imgClasses = function(converter) {
        return [
            {
                type: 'html',
                regex: '{: .(.*)}<img src=(.*)\/>',
                replace: '<img class="$1" src=$2>'
            }
        ];
    }
    var imgIds = function(converter) {
        return [
            {
                type: 'html',
                regex: '{: #(.*)}<img src=(.*)\/>',
                replace: '<img id="$1" src=$2>'
            }
        ];
    }
    //configure the extensions
    markdownConverterProvider.config({
      extensions: [imgClasses, imgIds],
      tables: true,
      parseImgDimensions: true
    });
`

Thank you for getting back to me!
